export const LOCAL_DOCUMENTS = [
  {
    id: "architecture",
    title: "Provider-neutral architecture",
    content:
      "Stackline AI keeps the frontend, server core, provider adapters, RAG retrievers, and memory stores separate. The UI calls your backend route. Provider keys and data access stay on the server.",
  },
  {
    id: "basic-mode",
    title: "Basic mode",
    content:
      "When rag and memory are disabled, Stackline AI behaves like a secure AI gateway. No database, migrations, memory store, or RAG store is required.",
  },
  {
    id: "rag-mode",
    title: "Local RAG demo",
    content:
      "This public demo uses a small in-memory document array as the RAG source. It does not connect to PostgreSQL, SQLite, Ollama Cloud, or any private service.",
  },
  {
    id: "ui",
    title: "Stackline AI Studio",
    content:
      "The Studio web component provides model selection, language selection, safe Markdown rendering, local history, RAG evidence display, and a customizable Material-inspired layout.",
  },
  {
    id: "security",
    title: "Security model",
    content:
      "Frontend applications should never expose provider API keys or database credentials. Use @stackline/ai-server or your backend route to proxy chat, model listing, RAG, and memory safely.",
  },
];

function normalize(value) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

function scoreDocument(query, document) {
  const normalizedQuery = normalize(query);
  const searchable = normalize(`${document.title} ${document.content}`);
  if (!normalizedQuery) return 0;
  if (searchable.includes(normalizedQuery)) return 100;

  return normalizedQuery
    .split(/\s+/)
    .filter((word) => word.length > 2 && searchable.includes(word)).length;
}

export function createLocalRetriever() {
  return {
    async retrieve(request) {
      const lastMessage = request.messages.at(-1)?.content || "";
      return LOCAL_DOCUMENTS.map((document) => ({
        document,
        score: scoreDocument(lastMessage, document),
      }))
        .filter((item) => item.score > 0)
        .sort((first, second) => second.score - first.score)
        .slice(0, 4)
        .map(({ document, score }) => ({
          content: `${document.title}\n\n${document.content}`,
          source: `local-docs:${document.id}`,
          score,
          metadata: {
            id: document.id,
            title: document.title,
          },
        }));
    },
  };
}

export function createDemoProvider() {
  return {
    name: "stackline-local-demo",
    capabilities: () => ({
      streaming: false,
      tools: false,
      vision: false,
      embeddings: false,
      modelListing: true,
      jsonMode: false,
      structuredOutput: false,
    }),
    listModels: async () => [
      { id: "demo-rag", name: "Demo RAG", provider: "local" },
      { id: "demo-fast", name: "Demo Fast", provider: "local" },
      { id: "demo-markdown", name: "Demo Markdown", provider: "local" },
    ],
    chat: async (request) => {
      const userMessage = request.messages.filter((message) => message.role === "user").at(-1)?.content || "";
      const ragContext = request.messages.find((message) => message.metadata?.stacklineRagContext === true);
      const model = request.model || "demo-rag";

      if (model === "demo-markdown") {
        return {
          role: "assistant",
          model,
          content: [
            "## Markdown and HTML safety",
            "",
            "This response is generated by the local demo provider.",
            "",
            "<p>Safe inline HTML is rendered as layout.</p>",
            "",
            "```html",
            "<stackline-ai-studio></stackline-ai-studio>",
            "```",
          ].join("\n"),
        };
      }

      if (ragContext) {
        return {
          role: "assistant",
          model,
          content: [
            "## Local RAG answer",
            "",
            "This answer used only the public in-memory documents bundled with the demo.",
            "",
            `Your question: ${userMessage}`,
            "",
            "The retrieved context says:",
            "",
            ragContext.content,
          ].join("\n"),
        };
      }

      return {
        role: "assistant",
        model,
        content: [
          "## Local demo provider",
          "",
          "This response came from the built-in demo provider. No external AI API, local Ollama instance, PostgreSQL database, SQLite memory store, or secret key was used.",
          "",
          `You asked: ${userMessage}`,
        ].join("\n"),
      };
    },
  };
}
